# Generated by Django 5.2.17 on 2026-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('Todo', 'Todo'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Done', 'Done')], default='Todo', max_length=20),
        ),
    ]
